# configs/arabic-asl-90kpts.yaml
# Configuration for Arabic Sign Language - 90 KEYPOINTS
# Uses MediaPipe Holistic: Upper Body Pose (23) + Left Hand (21) + Right Hand (21) + Face (25)

activation_dropout: 0.3
attention_dropout: 0.0
classifier_dropout: 0.7
d_model: 144
decoder_attention_heads: 8
decoder_ffn_dim: 144 
decoder_layerdrop: 0.4
decoder_layers: 2 
dropout: 0.3
encoder_attention_heads: 8
encoder_ffn_dim: 144
encoder_layerdrop: 0.4
encoder_layers: 2

# 90 KEYPOINTS from MediaPipe Holistic:
#   - Upper Body Pose: 23 landmarks (indices 0-22)
#   - Left Hand: 21 landmarks (indices 23-43)  
#   - Right Hand: 21 landmarks (indices 44-64)
#   - Face: 25 landmarks (indices 65-89) - SELECTED FROM 468 TOTAL
# 
# Pose landmarks (UPPER BODY ONLY - 23 points):
#   0: nose, 1-10: face, 11-16: upper body (shoulders/elbows/wrists), 17-22: hands
#   EXCLUDED: hips (23-24), knees (25-26), ankles (27-28), heels (29-30), feet (31-32)
#
# Face landmarks (selected from MediaPipe Face Mesh):
#   65-74: Face contour (10 points for head orientation)
#   75-81: Right eye (7 points for gaze and expression)
#   82-88: Left eye (7 points for gaze and expression)  
#   89: Nose tip (1 point for reference)
#
# The normalize_keypoints function will automatically group these as:
#   Group 1: Upper body pose (0-22) - normalized together
#   Group 2: Left hand (23-43) - normalized together
#   Group 3: Right hand (44-64) - normalized together
#   Group 4: Face (65-89) - normalized together

joint_idx:
  # Upper body pose ONLY (23 keypoints: 0-22)
  # Excludes lower body: hips, knees, ankles, heels, feet
  - 0   # nose
  - 1   # left_eye_inner
  - 2   # left_eye
  - 3   # left_eye_outer
  - 4   # right_eye_inner
  - 5   # right_eye
  - 6   # right_eye_outer
  - 7   # left_ear
  - 8   # right_ear
  - 9   # mouth_left
  - 10  # mouth_right
  - 11  # left_shoulder
  - 12  # right_shoulder
  - 13  # left_elbow
  - 14  # right_elbow
  - 15  # left_wrist
  - 16  # right_wrist
  - 17  # left_pinky
  - 18  # right_pinky
  - 19  # left_index
  - 20  # right_index
  - 21  # left_thumb
  - 22  # right_thumb
  # Left hand (21 keypoints: 23-43)
  - 23  # left_hand_wrist
  - 24  # left_hand_thumb_cmc
  - 25  # left_hand_thumb_mcp
  - 26  # left_hand_thumb_ip
  - 27  # left_hand_thumb_tip
  - 28  # left_hand_index_mcp
  - 29  # left_hand_index_pip
  - 30  # left_hand_index_dip
  - 31  # left_hand_index_tip
  - 32  # left_hand_middle_mcp
  - 33  # left_hand_middle_pip
  - 34  # left_hand_middle_dip
  - 35  # left_hand_middle_tip
  - 36  # left_hand_ring_mcp
  - 37  # left_hand_ring_pip
  - 38  # left_hand_ring_dip
  - 39  # left_hand_ring_tip
  - 40  # left_hand_pinky_mcp
  - 41  # left_hand_pinky_pip
  - 42  # left_hand_pinky_dip
  - 43  # left_hand_pinky_tip
  # Right hand (21 keypoints: 44-64)
  - 44  # right_hand_wrist
  - 45  # right_hand_thumb_cmc
  - 46  # right_hand_thumb_mcp
  - 47  # right_hand_thumb_ip
  - 48  # right_hand_thumb_tip
  - 49  # right_hand_index_mcp
  - 50  # right_hand_index_pip
  - 51  # right_hand_index_dip
  - 52  # right_hand_index_tip
  - 53  # right_hand_middle_mcp
  - 54  # right_hand_middle_pip
  - 55  # right_hand_middle_dip
  - 56  # right_hand_middle_tip
  - 57  # right_hand_ring_mcp
  - 58  # right_hand_ring_pip
  - 59  # right_hand_ring_dip
  - 60  # right_hand_ring_tip
  - 61  # right_hand_pinky_mcp
  - 62  # right_hand_pinky_pip
  - 63  # right_hand_pinky_dip
  - 64  # right_hand_pinky_tip
  # Face (25 keypoints: 65-89)
  # Selected symmetric landmarks from MediaPipe Face Mesh (468 total)
  - 65  # face_contour_1
  - 66  # face_contour_2
  - 67  # face_contour_3
  - 68  # face_contour_4
  - 69  # face_contour_5
  - 70  # face_contour_6
  - 71  # face_contour_7
  - 72  # face_contour_8
  - 73  # face_contour_9
  - 74  # face_contour_10
  - 75  # right_eye_1
  - 76  # right_eye_2
  - 77  # right_eye_3
  - 78  # right_eye_4
  - 79  # right_eye_5
  - 80  # right_eye_6
  - 81  # right_eye_7
  - 82  # left_eye_1
  - 83  # left_eye_2
  - 84  # left_eye_3
  - 85  # left_eye_4
  - 86  # left_eye_5
  - 87  # left_eye_6
  - 88  # left_eye_7
  - 89  # nose_tip

max_position_embeddings: 256
pe: learn  # learned positional embeddings
num_labels: 10

