# configs/arabic-asl-100kpts.yaml
# Configuration for Arabic Sign Language - 100 KEYPOINTS
# Uses MediaPipe Holistic: Pose (33) + Left Hand (21) + Right Hand (21) + Face (25)

activation_dropout: 0.3
attention_dropout: 0.0
classifier_dropout: 0.7
d_model: 144  # Increased from 128 since we have more keypoints (100 vs 75)
decoder_attention_heads: 8
decoder_ffn_dim: 144 
decoder_layerdrop: 0.4
decoder_layers: 2 
dropout: 0.3
encoder_attention_heads: 8
encoder_ffn_dim: 144
encoder_layerdrop: 0.4
encoder_layers: 2

# 100 KEYPOINTS from MediaPipe Holistic:
#   - Full Pose: 33 landmarks (indices 0-32)
#   - Left Hand: 21 landmarks (indices 33-53)  
#   - Right Hand: 21 landmarks (indices 54-74)
#   - Face: 25 landmarks (indices 75-99) - SELECTED FROM 468 TOTAL
# 
# Pose landmarks include:
#   0: nose, 1-10: face, 11-16: upper body (shoulders/elbows/wrists),
#   17-22: hands, 23-28: lower body (hips/knees/ankles), 29-32: feet
#
# Face landmarks (selected from MediaPipe Face Mesh):
#   75-84: Face contour (10 points for head orientation)
#   85-91: Right eye (7 points for gaze and expression)
#   92-98: Left eye (7 points for gaze and expression)  
#   99: Nose tip (1 point for reference)
#
# The normalize_keypoints function will automatically group these as:
#   Group 1: Body pose (0-32) - normalized together
#   Group 2: Left hand (33-53) - normalized together
#   Group 3: Right hand (54-74) - normalized together
#   Group 4: Face (75-99) - normalized together

joint_idx:
  # Full body pose (33 keypoints: 0-32)
  - 0   # nose
  - 1   # left_eye_inner
  - 2   # left_eye
  - 3   # left_eye_outer
  - 4   # right_eye_inner
  - 5   # right_eye
  - 6   # right_eye_outer
  - 7   # left_ear
  - 8   # right_ear
  - 9   # mouth_left
  - 10  # mouth_right
  - 11  # left_shoulder
  - 12  # right_shoulder
  - 13  # left_elbow
  - 14  # right_elbow
  - 15  # left_wrist
  - 16  # right_wrist
  - 17  # left_pinky
  - 18  # right_pinky
  - 19  # left_index
  - 20  # right_index
  - 21  # left_thumb
  - 22  # right_thumb
  - 23  # left_hip
  - 24  # right_hip
  - 25  # left_knee
  - 26  # right_knee
  - 27  # left_ankle
  - 28  # right_ankle
  - 29  # left_heel
  - 30  # right_heel
  - 31  # left_foot_index
  - 32  # right_foot_index
  # Left hand (21 keypoints: 33-53)
  - 33  # left_hand_wrist
  - 34  # left_hand_thumb_cmc
  - 35  # left_hand_thumb_mcp
  - 36  # left_hand_thumb_ip
  - 37  # left_hand_thumb_tip
  - 38  # left_hand_index_mcp
  - 39  # left_hand_index_pip
  - 40  # left_hand_index_dip
  - 41  # left_hand_index_tip
  - 42  # left_hand_middle_mcp
  - 43  # left_hand_middle_pip
  - 44  # left_hand_middle_dip
  - 45  # left_hand_middle_tip
  - 46  # left_hand_ring_mcp
  - 47  # left_hand_ring_pip
  - 48  # left_hand_ring_dip
  - 49  # left_hand_ring_tip
  - 50  # left_hand_pinky_mcp
  - 51  # left_hand_pinky_pip
  - 52  # left_hand_pinky_dip
  - 53  # left_hand_pinky_tip
  # Right hand (21 keypoints: 54-74)
  - 54  # right_hand_wrist
  - 55  # right_hand_thumb_cmc
  - 56  # right_hand_thumb_mcp
  - 57  # right_hand_thumb_ip
  - 58  # right_hand_thumb_tip
  - 59  # right_hand_index_mcp
  - 60  # right_hand_index_pip
  - 61  # right_hand_index_dip
  - 62  # right_hand_index_tip
  - 63  # right_hand_middle_mcp
  - 64  # right_hand_middle_pip
  - 65  # right_hand_middle_dip
  - 66  # right_hand_middle_tip
  - 67  # right_hand_ring_mcp
  - 68  # right_hand_ring_pip
  - 69  # right_hand_ring_dip
  - 70  # right_hand_ring_tip
  - 71  # right_hand_pinky_mcp
  - 72  # right_hand_pinky_pip
  - 73  # right_hand_pinky_dip
  - 74  # right_hand_pinky_tip
  # Face landmarks (25 keypoints: 75-99)
  # These correspond to specific MediaPipe Face Mesh indices:
  # Face contour: FM[10, 338, 297, 332, 284, 251, 389, 356, 454, 323]
  - 75   # face_contour_1 (FM 10 - forehead center)
  - 76   # face_contour_2 (FM 338 - right temple)
  - 77   # face_contour_3 (FM 297 - right cheek)
  - 78   # face_contour_4 (FM 332 - right jaw)
  - 79   # face_contour_5 (FM 284 - chin right)
  - 80   # face_contour_6 (FM 251 - chin center)
  - 81   # face_contour_7 (FM 389 - chin left)
  - 82   # face_contour_8 (FM 356 - left jaw)
  - 83   # face_contour_9 (FM 454 - left cheek)
  - 84   # face_contour_10 (FM 323 - left temple)
  # Right eye: FM[33, 133, 160, 159, 158, 144, 145]
  - 85   # right_eye_1 (FM 33 - right eye outer corner)
  - 86   # right_eye_2 (FM 133 - right eye inner corner)
  - 87   # right_eye_3 (FM 160 - right eye top outer)
  - 88   # right_eye_4 (FM 159 - right eye top center)
  - 89   # right_eye_5 (FM 158 - right eye top inner)
  - 90   # right_eye_6 (FM 144 - right eye bottom outer)
  - 91   # right_eye_7 (FM 145 - right eye bottom center)
  # Left eye: FM[362, 263, 387, 386, 385, 373, 374]
  - 92   # left_eye_1 (FM 362 - left eye inner corner)
  - 93   # left_eye_2 (FM 263 - left eye outer corner)
  - 94   # left_eye_3 (FM 387 - left eye top inner)
  - 95   # left_eye_4 (FM 386 - left eye top center)
  - 96   # left_eye_5 (FM 385 - left eye top outer)
  - 97   # left_eye_6 (FM 373 - left eye bottom inner)
  - 98   # left_eye_7 (FM 374 - left eye bottom center)
  # Nose: FM[1]
  - 99   # nose_tip (FM 1 - nose tip)

max_position_embeddings: 256
pe: "learn"
num_labels: 10  # 10 gestures (G01-G10)